version: 2.1

commands:
  print_pipeline_id: 
    description: "Udacity is the best platform to learn AWS"
    parameters:
      to:
        type: string
        default:  $CIRCLE_WORKFLOW_ID
    steps:
      - run:  echo << parameters.to >>

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output