version: 2.1

jobs:
  save-hello-world-output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Save Hello World Output"
          command: "echo 'Text to output here!' > output.txt"
      - presist_to_workspace:
        root:
          - /tmp/udacity
        paths:
          - demo/demo01

  print-output-file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
        name: "Print Output File"
        command: "cat output.txt"
      - attach_workspace:
        at: /tmp/udacity/demo/demo01

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-hello
      - print-world
        requires:
          - print-hello
